title: "Beyond"
description: "A fantasy novel project"
baseurl: ""  # Keep this empty for proper relative linking
url: ""

# Exclude unnecessary files
exclude:
  - README.md
  - LICENSE

# Enable the chapters collection
collections:
  chapters:
    output: true
    permalink: "/chapters/:name/"

# No theme (we're using custom styling)
theme: null
